from pydantic import BaseModel


class ingredient(BaseModel):
    간장: float
    고추기름: float
    감자: float
    고추가루: float
    고추장: float
    고추: float
    굴소스: float
    참기름: float
    김: float
    김치: float
    참깨: float
    통깨: float
    검은깨: float
    다시다: float
    다진마늘: float
    달걀: float
    당근: float
    대파: float
    돼지고기: float
    된장: float
    두부: float
    마늘: float
    마요네즈: float
    만두: float
    맛술: float
    물: float
    물엿: float
    숙주나물: float
    밥: float
    팽이버섯: float
    느타리버섯: float
    새송이버섯: float
    양송이버섯: float
    표고버섯: float
    버터: float
    베이컨: float
    설탕: float
    소고기: float
    소금: float
    소시지: float
    스팸: float
    식용유: float
    양배추: float
    양파: float
    연어: float
    옥수수: float
    쪽파: float
    참치: float
    청주: float
    치즈: float
    케찹: float
    햄: float
    애호박: float
    후추가루: float
    참치액젓: float
    콩나물: float
    어묵: float
    새우젓: float
    멸치: float
    멸치액젓: float
    명란: float
    생강: float
    황태: float
    무: float
    오징어: float
    우유: float
    사리: float
    치킨스톡: float
    다시마: float
    꽁치통조림: float
    당면: float
    고구마: float
    닭고기: float
    올리고당: float
    파프리카: float
    호박: float
    소면: float
    진미채: float
